spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/kstd
    username: root
    password: 1111

#  sql:
#    init:
#      mode: always

logging:
  level:
    com.kstd: INFO
    org.springframework.r2dbc: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui